import type { CollectionDefinition } from "@arche-cms/types";

import type { Generator, GeneratedFile, GenerationOptions } from "./generator.js";

function jsValue(val: unknown): string {
  if (val === null) return "null";
  if (typeof val === "string") return JSON.stringify(val);
  if (typeof val === "number" || typeof val === "boolean") return String(val);
  if (Array.isArray(val)) return `[${val.map(jsValue).join(", ")}]`;
  if (typeof val === "object") {
    const entries = Object.entries(val as Record<string, unknown>).filter(
      ([, v]) => v !== undefined,
    );
    if (entries.length === 0) return "{}";
    return `{ ${entries.map(([k, v]) => `${JSON.stringify(k)}: ${jsValue(v)}`).join(", ")} }`;
  }
  return String(val);
}

function generateValidationFile(collections: CollectionDefinition[]): string {
  const lines: string[] = [
    "// Auto-generated by @arche-cms/generators — do not edit manually",
    `import { z } from "zod";`,
    `import { fieldToZodSchema, collectionToCreateSchema, collectionToUpdateSchema } from "@arche-cms/validation";`,
    "",
  ];

  for (const col of collections) {
    const name = col.slug.replace(/[-.]/g, "_");
    lines.push(`const ${name}Def = ${jsValue(col)} as const;`);
    lines.push(`export const ${name}CreateSchema = collectionToCreateSchema(${name}Def);`);
    lines.push(`export const ${name}UpdateSchema = collectionToUpdateSchema(${name}Def);`);
    lines.push("");
  }

  return lines.join("\n");
}

export const validationGenerator: Generator = {
  description: "Generates Zod validation schemas from collection definitions",
  async generate(options: GenerationOptions): Promise<GeneratedFile[]> {
    if (!options.collections || options.collections.length === 0) return [];

    return [
      {
        content: generateValidationFile(options.collections),
        path: "validation/index.ts",
      },
    ];
  },
  name: "validation",
};
